-- GENERATED FILE — edit shared/seed-puzzles.js and run `npm run seed:sql`.
-- Initial puzzles. Apply once after schema:
--   wrangler d1 execute tabs-db --remote --file=./seed.sql
--
-- Every row below passes shared/submission.js's validateSubmission(),
-- the same validator the public /api/submit path uses — enforced by
-- shared/seed-puzzles.test.js.

INSERT OR IGNORE INTO puzzles (id, category, phrase, anchors, submitted_by, status) VALUES
  (1, 'MOVIE QUOTES', 'MAY THE FORCE BE WITH YOU', '[{"wi":2,"li":0},{"wi":4,"li":3}]', 'house', 'approved'),
  (2, 'FAMOUS SPEECHES', 'FOUR SCORE AND SEVEN YEARS', '[{"wi":1,"li":0},{"wi":3,"li":1}]', 'house', 'approved'),
  (3, 'BEATLES SONGS', 'HERE COMES THE SUN', '[{"wi":1,"li":0},{"wi":3,"li":2}]', 'house', 'approved'),
  (4, 'SHAKESPEARE', 'TO BE OR NOT TO BE', '[{"wi":1,"li":1},{"wi":3,"li":0}]', 'house', 'approved'),
  (5, 'PROVERBS', 'PRACTICE MAKES PERFECT', '[{"wi":0,"li":3},{"wi":1,"li":0}]', 'house', 'approved'),
  (6, 'FILM TITLES', 'GONE WITH THE WIND', '[{"wi":0,"li":0},{"wi":3,"li":3}]', 'house', 'approved'),
  (7, 'ROCK ANTHEMS', 'BORN IN THE USA', '[{"wi":0,"li":0},{"wi":3,"li":0}]', 'house', 'approved'),
  (8, 'MOTIVATIONAL', 'NEVER GIVE UP', '[{"wi":0,"li":0},{"wi":1,"li":0}]', 'house', 'approved'),
  (9, 'FAIRY TALES', 'HAPPILY EVER AFTER', '[{"wi":0,"li":0},{"wi":2,"li":0}]', 'house', 'approved'),
  (10, 'CARPE DIEM', 'SEIZE THE DAY', '[{"wi":0,"li":0},{"wi":2,"li":0}]', 'house', 'approved'),
  (1000, 'MOVIE QUOTES', 'HERE IS LOOKING AT YOU KID', '[{"wi":0,"li":1},{"wi":2,"li":0}]', 'house', 'approved'),
  (1001, 'MOVIE QUOTES', 'YOU CANT HANDLE THE TRUTH', '[{"wi":2,"li":0},{"wi":4,"li":1}]', 'house', 'approved'),
  (1002, 'MOVIE QUOTES', 'THERE IS NO PLACE LIKE HOME', '[{"wi":0,"li":0},{"wi":3,"li":1}]', 'house', 'approved'),
  (1003, 'MOVIE QUOTES', 'HOUSTON WE HAVE PROBLEM', '[{"wi":0,"li":0},{"wi":3,"li":1}]', 'house', 'approved'),
  (1004, 'MOVIE QUOTES', 'SHOW ME THE MONEY', '[{"wi":0,"li":1},{"wi":3,"li":0}]', 'house', 'approved'),
  (1005, 'MOVIE QUOTES', 'YOU TALKING TO ME', '[{"wi":0,"li":1},{"wi":1,"li":0}]', 'house', 'approved'),
  (1006, 'MOVIE QUOTES', 'LIFE IS LIKE BOX OF CHOCOLATES', '[{"wi":0,"li":1},{"wi":5,"li":0}]', 'house', 'approved'),
  (1007, 'MOVIE QUOTES', 'KEEP YOUR FRIENDS CLOSE', '[{"wi":2,"li":0},{"wi":3,"li":1}]', 'house', 'approved'),
  (1008, 'MOVIE QUOTES', 'TO INFINITY AND BEYOND', '[{"wi":1,"li":0},{"wi":3,"li":1}]', 'house', 'approved'),
  (1009, 'MOVIE QUOTES', 'JUST KEEP SWIMMING', '[{"wi":0,"li":1},{"wi":2,"li":0}]', 'house', 'approved'),
  (1010, 'MOVIE QUOTES', 'WHY SO SERIOUS', '[{"wi":0,"li":1},{"wi":2,"li":0}]', 'house', 'approved'),
  (1011, 'MOVIE QUOTES', 'HASTA LA VISTA BABY', '[{"wi":0,"li":0},{"wi":2,"li":1}]', 'house', 'approved'),
  (1012, 'MOVIE QUOTES', 'GO AHEAD MAKE MY DAY', '[{"wi":1,"li":0},{"wi":2,"li":1}]', 'house', 'approved'),
  (1013, 'MOVIE QUOTES', 'NOBODY PUTS BABY IN THE CORNER', '[{"wi":0,"li":0},{"wi":5,"li":1}]', 'house', 'approved'),
  (1014, 'MOVIE QUOTES', 'THE FIRST RULE OF FIGHT CLUB', '[{"wi":1,"li":0},{"wi":4,"li":1}]', 'house', 'approved'),
  (1015, 'MOVIE QUOTES', 'MY PRECIOUS', '[{"wi":0,"li":0},{"wi":1,"li":0}]', 'house', 'approved'),
  (1016, 'MOVIE QUOTES', 'YOU SHALL NOT PASS', '[{"wi":1,"li":0},{"wi":3,"li":1}]', 'house', 'approved'),
  (1017, 'MOVIE QUOTES', 'WE ARE GOING TO NEED BIGGER BOAT', '[{"wi":2,"li":1},{"wi":5,"li":0}]', 'house', 'approved'),
  (1018, 'MOVIE QUOTES', 'SAY HELLO TO MY LITTLE FRIEND', '[{"wi":4,"li":0},{"wi":5,"li":1}]', 'house', 'approved'),
  (1019, 'MOVIE QUOTES', 'THIS IS SPARTA', '[{"wi":0,"li":1},{"wi":2,"li":0}]', 'house', 'approved'),
  (1020, 'MOVIE QUOTES', 'ROADS WHERE WE ARE GOING WE DONT NEED ROADS', '[{"wi":0,"li":0},{"wi":1,"li":1}]', 'house', 'approved'),
  (1021, 'MOVIE QUOTES', 'THE STUFF THAT DREAMS ARE MADE OF', '[{"wi":1,"li":1},{"wi":3,"li":0}]', 'house', 'approved'),
  (1022, 'FILM TITLES', 'THE SHAWSHANK REDEMPTION', '[{"wi":1,"li":1},{"wi":2,"li":0}]', 'house', 'approved'),
  (1023, 'FILM TITLES', 'PULP FICTION', '[{"wi":0,"li":1},{"wi":1,"li":0}]', 'house', 'approved'),
  (1024, 'FILM TITLES', 'THE DARK KNIGHT', '[{"wi":1,"li":1},{"wi":2,"li":0}]', 'house', 'approved'),
  (1025, 'FILM TITLES', 'FORREST GUMP', '[{"wi":0,"li":0},{"wi":1,"li":1}]', 'house', 'approved'),
  (1026, 'FILM TITLES', 'THE GODFATHER', '[{"wi":0,"li":1},{"wi":1,"li":0}]', 'house', 'approved'),
  (1027, 'FILM TITLES', 'BACK TO THE FUTURE', '[{"wi":0,"li":1},{"wi":3,"li":0}]', 'house', 'approved'),
  (1028, 'FILM TITLES', 'THE LION KING', '[{"wi":1,"li":0},{"wi":2,"li":1}]', 'house', 'approved'),
  (1029, 'FILM TITLES', 'JURASSIC PARK', '[{"wi":0,"li":0},{"wi":1,"li":1}]', 'house', 'approved'),
  (1030, 'FILM TITLES', 'THE MATRIX', '[{"wi":0,"li":1},{"wi":1,"li":0}]', 'house', 'approved'),
  (1031, 'FILM TITLES', 'FINDING NEMO', '[{"wi":0,"li":0},{"wi":1,"li":1}]', 'house', 'approved'),
  (1032, 'FILM TITLES', 'THE SILENCE OF THE LAMBS', '[{"wi":1,"li":0},{"wi":4,"li":1}]', 'house', 'approved'),
  (1033, 'FILM TITLES', 'SINGING IN THE RAIN', '[{"wi":0,"li":0},{"wi":3,"li":1}]', 'house', 'approved'),
  (1034, 'FILM TITLES', 'SOME LIKE IT HOT', '[{"wi":0,"li":0},{"wi":1,"li":1}]', 'house', 'approved'),
  (1035, 'FILM TITLES', 'THE WIZARD OF OZ', '[{"wi":0,"li":1},{"wi":1,"li":0}]', 'house', 'approved'),
  (1036, 'FILM TITLES', 'ITS WONDERFUL LIFE', '[{"wi":1,"li":0},{"wi":2,"li":1}]', 'house', 'approved'),
  (1037, 'FILM TITLES', 'RAIDERS OF THE LOST ARK', '[{"wi":0,"li":0},{"wi":3,"li":1}]', 'house', 'approved'),
  (1038, 'FILM TITLES', 'THE PRINCESS BRIDE', '[{"wi":1,"li":0},{"wi":2,"li":1}]', 'house', 'approved'),
  (1039, 'FILM TITLES', 'GOOD WILL HUNTING', '[{"wi":0,"li":1},{"wi":2,"li":0}]', 'house', 'approved'),
  (1040, 'FILM TITLES', 'THE GRAND BUDAPEST HOTEL', '[{"wi":1,"li":1},{"wi":2,"li":0}]', 'house', 'approved'),
  (1041, 'FILM TITLES', 'SPIRITED AWAY', '[{"wi":0,"li":0},{"wi":1,"li":1}]', 'house', 'approved'),
  (1042, 'FILM TITLES', 'MAD MAX FURY ROAD', '[{"wi":2,"li":0},{"wi":3,"li":1}]', 'house', 'approved'),
  (1043, 'FILM TITLES', 'EVERYTHING EVERYWHERE ALL AT ONCE', '[{"wi":0,"li":0},{"wi":1,"li":1}]', 'house', 'approved'),
  (1044, 'TV SHOWS', 'BREAKING BAD', '[{"wi":0,"li":0},{"wi":1,"li":1}]', 'house', 'approved'),
  (1045, 'TV SHOWS', 'GAME OF THRONES', '[{"wi":0,"li":1},{"wi":2,"li":0}]', 'house', 'approved'),
  (1046, 'TV SHOWS', 'THE OFFICE', '[{"wi":0,"li":1},{"wi":1,"li":0}]', 'house', 'approved'),
  (1047, 'TV SHOWS', 'PARKS AND RECREATION', '[{"wi":0,"li":1},{"wi":2,"li":0}]', 'house', 'approved'),
  (1048, 'TV SHOWS', 'STRANGER THINGS', '[{"wi":0,"li":0},{"wi":1,"li":1}]', 'house', 'approved'),
  (1049, 'TV SHOWS', 'THE SOPRANOS', '[{"wi":0,"li":1},{"wi":1,"li":0}]', 'house', 'approved'),
  (1050, 'TV SHOWS', 'THE WIRE', '[{"wi":0,"li":1},{"wi":1,"li":0}]', 'house', 'approved'),
  (1051, 'TV SHOWS', 'MAD MEN', '[{"wi":0,"li":0},{"wi":1,"li":1}]', 'house', 'approved'),
  (1052, 'TV SHOWS', 'CURB YOUR ENTHUSIASM', '[{"wi":0,"li":1},{"wi":2,"li":0}]', 'house', 'approved'),
  (1053, 'TV SHOWS', 'THE GOOD PLACE', '[{"wi":1,"li":1},{"wi":2,"li":0}]', 'house', 'approved'),
  (1054, 'TV SHOWS', 'TED LASSO', '[{"wi":0,"li":1},{"wi":1,"li":0}]', 'house', 'approved'),
  (1055, 'TV SHOWS', 'THE CROWN', '[{"wi":0,"li":1},{"wi":1,"li":0}]', 'house', 'approved'),
  (1056, 'TV SHOWS', 'BETTER CALL SAUL', '[{"wi":0,"li":0},{"wi":1,"li":1}]', 'house', 'approved'),
  (1057, 'TV SHOWS', 'THE BIG BANG THEORY', '[{"wi":2,"li":1},{"wi":3,"li":0}]', 'house', 'approved'),
  (1058, 'TV SHOWS', 'TWIN PEAKS', '[{"wi":0,"li":1},{"wi":1,"li":0}]', 'house', 'approved'),
  (1059, 'TV SHOWS', 'THE SIMPSONS', '[{"wi":0,"li":1},{"wi":1,"li":0}]', 'house', 'approved'),
  (1060, 'TV SHOWS', 'DOCTOR WHO', '[{"wi":0,"li":0},{"wi":1,"li":1}]', 'house', 'approved'),
  (1061, 'TV SHOWS', 'THE WEST WING', '[{"wi":1,"li":0},{"wi":2,"li":1}]', 'house', 'approved'),
  (1062, 'TV SHOWS', 'THE WALKING DEAD', '[{"wi":1,"li":0},{"wi":2,"li":1}]', 'house', 'approved'),
  (1063, 'TV SHOWS', 'ONLY MURDERS IN THE BUILDING', '[{"wi":1,"li":1},{"wi":4,"li":0}]', 'house', 'approved'),
  (1064, 'SONG TITLES', 'BOHEMIAN RHAPSODY', '[{"wi":0,"li":0},{"wi":1,"li":1}]', 'house', 'approved'),
  (1065, 'SONG TITLES', 'STAIRWAY TO HEAVEN', '[{"wi":0,"li":0},{"wi":2,"li":1}]', 'house', 'approved'),
  (1066, 'SONG TITLES', 'LIKE ROLLING STONE', '[{"wi":1,"li":0},{"wi":2,"li":1}]', 'house', 'approved'),
  (1067, 'SONG TITLES', 'SMELLS LIKE TEEN SPIRIT', '[{"wi":0,"li":0},{"wi":3,"li":1}]', 'house', 'approved'),
  (1068, 'SONG TITLES', 'IMAGINE ALL THE PEOPLE', '[{"wi":0,"li":0},{"wi":3,"li":1}]', 'house', 'approved'),
  (1069, 'SONG TITLES', 'HOTEL CALIFORNIA', '[{"wi":0,"li":1},{"wi":1,"li":0}]', 'house', 'approved'),
  (1070, 'SONG TITLES', 'SWEET CHILD OF MINE', '[{"wi":0,"li":0},{"wi":1,"li":1}]', 'house', 'approved'),
  (1071, 'SONG TITLES', 'DANCING QUEEN', '[{"wi":0,"li":0},{"wi":1,"li":1}]', 'house', 'approved'),
  (1072, 'SONG TITLES', 'BILLIE JEAN', '[{"wi":0,"li":0},{"wi":1,"li":1}]', 'house', 'approved'),
  (1073, 'SONG TITLES', 'PURPLE RAIN', '[{"wi":0,"li":0},{"wi":1,"li":1}]', 'house', 'approved'),
  (1074, 'SONG TITLES', 'SWEET CAROLINE', '[{"wi":0,"li":1},{"wi":1,"li":0}]', 'house', 'approved'),
  (1075, 'SONG TITLES', 'DONT STOP BELIEVING', '[{"wi":0,"li":1},{"wi":2,"li":0}]', 'house', 'approved'),
  (1076, 'SONG TITLES', 'LOSE YOURSELF', '[{"wi":0,"li":1},{"wi":1,"li":0}]', 'house', 'approved'),
  (1077, 'SONG TITLES', 'ROLLING IN THE DEEP', '[{"wi":0,"li":0},{"wi":3,"li":1}]', 'house', 'approved'),
  (1078, 'SONG TITLES', 'SHAKE IT OFF', '[{"wi":0,"li":0},{"wi":2,"li":1}]', 'house', 'approved'),
  (1079, 'SONG TITLES', 'UPTOWN FUNK', '[{"wi":0,"li":0},{"wi":1,"li":1}]', 'house', 'approved'),
  (1080, 'SONG TITLES', 'BLINDING LIGHTS', '[{"wi":0,"li":0},{"wi":1,"li":1}]', 'house', 'approved'),
  (1081, 'SONG TITLES', 'MR BRIGHTSIDE', '[{"wi":0,"li":0},{"wi":1,"li":0}]', 'house', 'approved'),
  (1082, 'SONG TITLES', 'SEVEN NATION ARMY', '[{"wi":0,"li":1},{"wi":1,"li":0}]', 'house', 'approved'),
  (1083, 'SONG TITLES', 'CRAZY IN LOVE', '[{"wi":0,"li":0},{"wi":2,"li":1}]', 'house', 'approved'),
  (1084, 'SONG TITLES', 'TAKE ME HOME COUNTRY ROADS', '[{"wi":3,"li":0},{"wi":4,"li":1}]', 'house', 'approved'),
  (1085, 'SONG TITLES', 'WHAT WONDERFUL WORLD', '[{"wi":1,"li":0},{"wi":2,"li":1}]', 'house', 'approved'),
  (1086, 'BEATLES SONGS', 'LET IT BE', '[{"wi":0,"li":0},{"wi":1,"li":0}]', 'house', 'approved'),
  (1087, 'BEATLES SONGS', 'HEY JUDE', '[{"wi":0,"li":1},{"wi":1,"li":0}]', 'house', 'approved'),
  (1088, 'BEATLES SONGS', 'LUCY IN THE SKY WITH DIAMONDS', '[{"wi":0,"li":1},{"wi":5,"li":0}]', 'house', 'approved'),
  (1089, 'BEATLES SONGS', 'COME TOGETHER', '[{"wi":0,"li":1},{"wi":1,"li":0}]', 'house', 'approved'),
  (1090, 'BEATLES SONGS', 'ALL YOU NEED IS LOVE', '[{"wi":2,"li":0},{"wi":4,"li":1}]', 'house', 'approved'),
  (1091, 'BEATLES SONGS', 'STRAWBERRY FIELDS FOREVER', '[{"wi":0,"li":0},{"wi":2,"li":1}]', 'house', 'approved'),
  (1092, 'BEATLES SONGS', 'PENNY LANE', '[{"wi":0,"li":0},{"wi":1,"li":1}]', 'house', 'approved'),
  (1093, 'BEATLES SONGS', 'YELLOW SUBMARINE', '[{"wi":0,"li":1},{"wi":1,"li":0}]', 'house', 'approved'),
  (1094, 'BEATLES SONGS', 'ELEANOR RIGBY', '[{"wi":0,"li":0},{"wi":1,"li":1}]', 'house', 'approved'),
  (1095, 'BEATLES SONGS', 'CANT BUY ME LOVE', '[{"wi":0,"li":0},{"wi":3,"li":1}]', 'house', 'approved'),
  (1096, 'BEATLES SONGS', 'TWIST AND SHOUT', '[{"wi":0,"li":0},{"wi":2,"li":1}]', 'house', 'approved'),
  (1097, 'BEATLES SONGS', 'WHILE MY GUITAR GENTLY WEEPS', '[{"wi":2,"li":0},{"wi":3,"li":1}]', 'house', 'approved'),
  (1098, 'BEATLES SONGS', 'NORWEGIAN WOOD', '[{"wi":0,"li":0},{"wi":1,"li":1}]', 'house', 'approved'),
  (1099, 'BEATLES SONGS', 'IN MY LIFE', '[{"wi":0,"li":0},{"wi":2,"li":0}]', 'house', 'approved'),
  (1100, 'BEATLES SONGS', 'HERE THERE AND EVERYWHERE', '[{"wi":1,"li":1},{"wi":3,"li":0}]', 'house', 'approved'),
  (1101, 'BEATLES SONGS', 'THE LONG AND WINDING ROAD', '[{"wi":1,"li":1},{"wi":3,"li":0}]', 'house', 'approved'),
  (1102, 'BEATLES SONGS', 'WITH LITTLE HELP FROM MY FRIENDS', '[{"wi":1,"li":1},{"wi":5,"li":0}]', 'house', 'approved'),
  (1103, 'BEATLES SONGS', 'OB LA DI OB LA DA', '[{"wi":0,"li":0},{"wi":1,"li":0}]', 'house', 'approved'),
  (1104, 'ROCK ANTHEMS', 'WE WILL ROCK YOU', '[{"wi":1,"li":0},{"wi":2,"li":1}]', 'house', 'approved'),
  (1105, 'ROCK ANTHEMS', 'LIVING ON PRAYER', '[{"wi":0,"li":0},{"wi":2,"li":1}]', 'house', 'approved'),
  (1106, 'ROCK ANTHEMS', 'BACK IN BLACK', '[{"wi":0,"li":1},{"wi":2,"li":0}]', 'house', 'approved'),
  (1107, 'ROCK ANTHEMS', 'ENTER SANDMAN', '[{"wi":0,"li":1},{"wi":1,"li":0}]', 'house', 'approved'),
  (1108, 'ROCK ANTHEMS', 'WELCOME TO THE JUNGLE', '[{"wi":0,"li":0},{"wi":3,"li":1}]', 'house', 'approved'),
  (1109, 'ROCK ANTHEMS', 'IRON MAN', '[{"wi":0,"li":0},{"wi":1,"li":1}]', 'house', 'approved'),
  (1110, 'ROCK ANTHEMS', 'HIGHWAY TO HELL', '[{"wi":0,"li":0},{"wi":2,"li":1}]', 'house', 'approved'),
  (1111, 'ROCK ANTHEMS', 'FREE BIRD', '[{"wi":0,"li":0},{"wi":1,"li":1}]', 'house', 'approved'),
  (1112, 'ROCK ANTHEMS', 'MORE THAN FEELING', '[{"wi":0,"li":1},{"wi":2,"li":0}]', 'house', 'approved'),
  (1113, 'ROCK ANTHEMS', 'EYE OF THE TIGER', '[{"wi":0,"li":1},{"wi":3,"li":0}]', 'house', 'approved'),
  (1114, 'ROCK ANTHEMS', 'THE FINAL COUNTDOWN', '[{"wi":1,"li":1},{"wi":2,"li":0}]', 'house', 'approved'),
  (1115, 'ROCK ANTHEMS', 'DREAM ON', '[{"wi":0,"li":0},{"wi":1,"li":0}]', 'house', 'approved'),
  (1116, 'ROCK ANTHEMS', 'WHOLE LOTTA LOVE', '[{"wi":0,"li":0},{"wi":1,"li":1}]', 'house', 'approved'),
  (1117, 'ROCK ANTHEMS', 'SMOKE ON THE WATER', '[{"wi":0,"li":0},{"wi":3,"li":1}]', 'house', 'approved'),
  (1118, 'ROCK ANTHEMS', 'ANOTHER BRICK IN THE WALL', '[{"wi":0,"li":0},{"wi":1,"li":1}]', 'house', 'approved'),
  (1119, 'ROCK ANTHEMS', 'SWEET HOME ALABAMA', '[{"wi":0,"li":1},{"wi":2,"li":0}]', 'house', 'approved'),
  (1120, 'ROCK ANTHEMS', 'BAD MOON RISING', '[{"wi":1,"li":1},{"wi":2,"li":0}]', 'house', 'approved'),
  (1121, 'ROCK ANTHEMS', 'BORN TO RUN', '[{"wi":0,"li":0},{"wi":2,"li":1}]', 'house', 'approved'),
  (1122, 'ROCK ANTHEMS', 'ROCK AND ROLL ALL NITE', '[{"wi":0,"li":0},{"wi":2,"li":1}]', 'house', 'approved'),
  (1123, 'ROCK ANTHEMS', 'IMMIGRANT SONG', '[{"wi":0,"li":0},{"wi":1,"li":1}]', 'house', 'approved'),
  (1124, 'BOOK TITLES', 'PRIDE AND PREJUDICE', '[{"wi":0,"li":1},{"wi":2,"li":0}]', 'house', 'approved'),
  (1125, 'BOOK TITLES', 'ANIMAL FARM', '[{"wi":0,"li":0},{"wi":1,"li":1}]', 'house', 'approved'),
  (1126, 'BOOK TITLES', 'THE GREAT GATSBY', '[{"wi":1,"li":1},{"wi":2,"li":0}]', 'house', 'approved'),
  (1127, 'BOOK TITLES', 'ONE HUNDRED YEARS OF SOLITUDE', '[{"wi":1,"li":1},{"wi":4,"li":0}]', 'house', 'approved'),
  (1128, 'BOOK TITLES', 'THE CATCHER IN THE RYE', '[{"wi":0,"li":1},{"wi":1,"li":0}]', 'house', 'approved'),
  (1129, 'BOOK TITLES', 'BRAVE NEW WORLD', '[{"wi":0,"li":0},{"wi":2,"li":1}]', 'house', 'approved'),
  (1130, 'BOOK TITLES', 'THE HOBBIT', '[{"wi":0,"li":1},{"wi":1,"li":0}]', 'house', 'approved'),
  (1131, 'BOOK TITLES', 'CRIME AND PUNISHMENT', '[{"wi":0,"li":1},{"wi":2,"li":0}]', 'house', 'approved'),
  (1132, 'BOOK TITLES', 'WAR AND PEACE', '[{"wi":0,"li":1},{"wi":2,"li":0}]', 'house', 'approved'),
  (1133, 'BOOK TITLES', 'THE GRAPES OF WRATH', '[{"wi":1,"li":0},{"wi":3,"li":1}]', 'house', 'approved'),
  (1134, 'BOOK TITLES', 'OF MICE AND MEN', '[{"wi":1,"li":0},{"wi":2,"li":1}]', 'house', 'approved'),
  (1135, 'BOOK TITLES', 'THE OLD MAN AND THE SEA', '[{"wi":0,"li":0},{"wi":1,"li":1}]', 'house', 'approved'),
  (1136, 'BOOK TITLES', 'LORD OF THE FLIES', '[{"wi":0,"li":1},{"wi":3,"li":0}]', 'house', 'approved'),
  (1137, 'BOOK TITLES', 'THE HANDMAIDS TALE', '[{"wi":1,"li":0},{"wi":2,"li":1}]', 'house', 'approved'),
  (1138, 'BOOK TITLES', 'THE ROAD', '[{"wi":0,"li":1},{"wi":1,"li":0}]', 'house', 'approved'),
  (1139, 'BOOK TITLES', 'JANE EYRE', '[{"wi":0,"li":0},{"wi":1,"li":1}]', 'house', 'approved'),
  (1140, 'BOOK TITLES', 'WUTHERING HEIGHTS', '[{"wi":0,"li":0},{"wi":1,"li":1}]', 'house', 'approved'),
  (1141, 'BOOK TITLES', 'THE COLOR PURPLE', '[{"wi":1,"li":1},{"wi":2,"li":0}]', 'house', 'approved'),
  (1142, 'BOOK TITLES', 'MOBY DICK', '[{"wi":0,"li":0},{"wi":1,"li":1}]', 'house', 'approved'),
  (1143, 'BOOK TITLES', 'THE SUN ALSO RISES', '[{"wi":2,"li":1},{"wi":3,"li":0}]', 'house', 'approved'),
  (1144, 'BOOK TITLES', 'THINGS FALL APART', '[{"wi":0,"li":0},{"wi":2,"li":1}]', 'house', 'approved'),
  (1145, 'BOOK TITLES', 'CATCH TWENTY TWO', '[{"wi":0,"li":1},{"wi":1,"li":0}]', 'house', 'approved'),
  (1146, 'SHAKESPEARE', 'ALL THE WORLDS STAGE', '[{"wi":2,"li":0},{"wi":3,"li":1}]', 'house', 'approved'),
  (1147, 'SHAKESPEARE', 'TO THINE OWN SELF BE TRUE', '[{"wi":1,"li":0},{"wi":3,"li":1}]', 'house', 'approved'),
  (1148, 'SHAKESPEARE', 'THE COURSE OF TRUE LOVE', '[{"wi":1,"li":0},{"wi":3,"li":1}]', 'house', 'approved'),
  (1149, 'SHAKESPEARE', 'BREVITY IS THE SOUL OF WIT', '[{"wi":0,"li":0},{"wi":3,"li":1}]', 'house', 'approved'),
  (1150, 'SHAKESPEARE', 'ALL THAT GLITTERS IS NOT GOLD', '[{"wi":1,"li":1},{"wi":2,"li":0}]', 'house', 'approved'),
  (1151, 'SHAKESPEARE', 'THE LADY DOTH PROTEST TOO MUCH', '[{"wi":1,"li":1},{"wi":3,"li":0}]', 'house', 'approved'),
  (1152, 'SHAKESPEARE', 'NOW IS THE WINTER OF OUR DISCONTENT', '[{"wi":3,"li":1},{"wi":6,"li":0}]', 'house', 'approved'),
  (1153, 'SHAKESPEARE', 'ONCE MORE UNTO THE BREACH', '[{"wi":0,"li":1},{"wi":4,"li":0}]', 'house', 'approved'),
  (1154, 'SHAKESPEARE', 'PARTING IS SUCH SWEET SORROW', '[{"wi":0,"li":0},{"wi":4,"li":1}]', 'house', 'approved'),
  (1155, 'SHAKESPEARE', 'SOMETHING IS ROTTEN IN THE STATE', '[{"wi":0,"li":0},{"wi":2,"li":1}]', 'house', 'approved'),
  (1156, 'SHAKESPEARE', 'THE WORLD IS MINE OYSTER', '[{"wi":1,"li":1},{"wi":4,"li":0}]', 'house', 'approved'),
  (1157, 'SHAKESPEARE', 'WHAT LIGHT THROUGH YONDER WINDOW', '[{"wi":2,"li":0},{"wi":3,"li":1}]', 'house', 'approved'),
  (1158, 'SHAKESPEARE', 'ET TU BRUTE', '[{"wi":0,"li":0},{"wi":2,"li":0}]', 'house', 'approved'),
  (1159, 'SHAKESPEARE', 'OUT DAMNED SPOT', '[{"wi":1,"li":0},{"wi":2,"li":1}]', 'house', 'approved'),
  (1160, 'SHAKESPEARE', 'WE FEW WE HAPPY FEW', '[{"wi":1,"li":1},{"wi":3,"li":0}]', 'house', 'approved'),
  (1161, 'SHAKESPEARE', 'DOUBLE DOUBLE TOIL AND TROUBLE', '[{"wi":0,"li":1},{"wi":4,"li":0}]', 'house', 'approved'),
  (1162, 'SHAKESPEARE', 'THE BETTER PART OF VALOR', '[{"wi":1,"li":0},{"wi":4,"li":1}]', 'house', 'approved'),
  (1163, 'SHAKESPEARE', 'SUCH STUFF AS DREAMS ARE MADE ON', '[{"wi":1,"li":1},{"wi":3,"li":0}]', 'house', 'approved'),
  (1164, 'PROVERBS', 'ACTIONS SPEAK LOUDER THAN WORDS', '[{"wi":0,"li":0},{"wi":2,"li":1}]', 'house', 'approved'),
  (1165, 'PROVERBS', 'THE EARLY BIRD CATCHES THE WORM', '[{"wi":1,"li":1},{"wi":3,"li":0}]', 'house', 'approved'),
  (1166, 'PROVERBS', 'BETTER LATE THAN NEVER', '[{"wi":0,"li":0},{"wi":3,"li":1}]', 'house', 'approved'),
  (1167, 'PROVERBS', 'TWO WRONGS DONT MAKE RIGHT', '[{"wi":1,"li":0},{"wi":4,"li":1}]', 'house', 'approved'),
  (1168, 'PROVERBS', 'WHEN IN ROME DO AS THE ROMANS', '[{"wi":0,"li":1},{"wi":6,"li":0}]', 'house', 'approved'),
  (1169, 'PROVERBS', 'THE PEN IS MIGHTIER THAN THE SWORD', '[{"wi":3,"li":0},{"wi":6,"li":1}]', 'house', 'approved'),
  (1170, 'PROVERBS', 'FORTUNE FAVORS THE BOLD', '[{"wi":0,"li":0},{"wi":1,"li":1}]', 'house', 'approved'),
  (1171, 'PROVERBS', 'HONESTY IS THE BEST POLICY', '[{"wi":0,"li":0},{"wi":4,"li":1}]', 'house', 'approved'),
  (1172, 'PROVERBS', 'LOOK BEFORE YOU LEAP', '[{"wi":0,"li":1},{"wi":1,"li":0}]', 'house', 'approved'),
  (1173, 'PROVERBS', 'MANY HANDS MAKE LIGHT WORK', '[{"wi":1,"li":0},{"wi":3,"li":1}]', 'house', 'approved'),
  (1174, 'PROVERBS', 'NO PAIN NO GAIN', '[{"wi":1,"li":0},{"wi":3,"li":1}]', 'house', 'approved'),
  (1175, 'PROVERBS', 'SLOW AND STEADY WINS THE RACE', '[{"wi":0,"li":1},{"wi":2,"li":0}]', 'house', 'approved'),
  (1176, 'PROVERBS', 'TOO MANY COOKS SPOIL THE BROTH', '[{"wi":2,"li":0},{"wi":3,"li":1}]', 'house', 'approved'),
  (1177, 'PROVERBS', 'YOU REAP WHAT YOU SOW', '[{"wi":1,"li":0},{"wi":2,"li":1}]', 'house', 'approved'),
  (1178, 'PROVERBS', 'STILL WATERS RUN DEEP', '[{"wi":0,"li":1},{"wi":1,"li":0}]', 'house', 'approved'),
  (1179, 'PROVERBS', 'EVERY CLOUD HAS SILVER LINING', '[{"wi":3,"li":0},{"wi":4,"li":1}]', 'house', 'approved'),
  (1180, 'PROVERBS', 'THE GRASS IS ALWAYS GREENER', '[{"wi":3,"li":1},{"wi":4,"li":0}]', 'house', 'approved'),
  (1181, 'PROVERBS', 'BIRDS OF FEATHER FLOCK TOGETHER', '[{"wi":2,"li":1},{"wi":4,"li":0}]', 'house', 'approved'),
  (1182, 'PROVERBS', 'ROME WAS NOT BUILT IN DAY', '[{"wi":0,"li":1},{"wi":3,"li":0}]', 'house', 'approved'),
  (1183, 'PROVERBS', 'DONT COUNT YOUR CHICKENS', '[{"wi":1,"li":1},{"wi":3,"li":0}]', 'house', 'approved'),
  (1184, 'PROVERBS', 'ABSENCE MAKES THE HEART GROW FONDER', '[{"wi":0,"li":0},{"wi":5,"li":1}]', 'house', 'approved'),
  (1185, 'PROVERBS', 'ONE GOOD TURN DESERVES ANOTHER', '[{"wi":3,"li":0},{"wi":4,"li":1}]', 'house', 'approved'),
  (1186, 'IDIOMS', 'BREAK THE ICE', '[{"wi":0,"li":0},{"wi":1,"li":1}]', 'house', 'approved'),
  (1187, 'IDIOMS', 'BITE THE BULLET', '[{"wi":0,"li":1},{"wi":2,"li":0}]', 'house', 'approved'),
  (1188, 'IDIOMS', 'SPILL THE BEANS', '[{"wi":0,"li":0},{"wi":2,"li":1}]', 'house', 'approved'),
  (1189, 'IDIOMS', 'ONCE IN BLUE MOON', '[{"wi":0,"li":0},{"wi":2,"li":1}]', 'house', 'approved'),
  (1190, 'IDIOMS', 'PIECE OF CAKE', '[{"wi":0,"li":0},{"wi":2,"li":1}]', 'house', 'approved'),
  (1191, 'IDIOMS', 'UNDER THE WEATHER', '[{"wi":0,"li":1},{"wi":2,"li":0}]', 'house', 'approved'),
  (1192, 'IDIOMS', 'HIT THE NAIL ON THE HEAD', '[{"wi":2,"li":0},{"wi":5,"li":1}]', 'house', 'approved'),
  (1193, 'IDIOMS', 'THE BALL IS IN YOUR COURT', '[{"wi":1,"li":1},{"wi":5,"li":0}]', 'house', 'approved'),
  (1194, 'IDIOMS', 'LET THE CAT OUT OF THE BAG', '[{"wi":0,"li":0},{"wi":1,"li":1}]', 'house', 'approved'),
  (1195, 'IDIOMS', 'COST AN ARM AND LEG', '[{"wi":0,"li":0},{"wi":2,"li":1}]', 'house', 'approved'),
  (1196, 'IDIOMS', 'BURN THE MIDNIGHT OIL', '[{"wi":0,"li":1},{"wi":2,"li":0}]', 'house', 'approved'),
  (1197, 'IDIOMS', 'CUT TO THE CHASE', '[{"wi":0,"li":1},{"wi":3,"li":0}]', 'house', 'approved'),
  (1198, 'IDIOMS', 'THE ELEPHANT IN THE ROOM', '[{"wi":1,"li":0},{"wi":4,"li":1}]', 'house', 'approved'),
  (1199, 'IDIOMS', 'BARKING UP THE WRONG TREE', '[{"wi":0,"li":0},{"wi":3,"li":1}]', 'house', 'approved'),
  (1200, 'IDIOMS', 'BEAT AROUND THE BUSH', '[{"wi":0,"li":1},{"wi":1,"li":0}]', 'house', 'approved'),
  (1201, 'IDIOMS', 'CALL IT DAY', '[{"wi":0,"li":0},{"wi":2,"li":1}]', 'house', 'approved'),
  (1202, 'IDIOMS', 'ON THE SAME PAGE', '[{"wi":2,"li":0},{"wi":3,"li":1}]', 'house', 'approved'),
  (1203, 'IDIOMS', 'PULL YOURSELF TOGETHER', '[{"wi":1,"li":0},{"wi":2,"li":1}]', 'house', 'approved'),
  (1204, 'IDIOMS', 'THROW IN THE TOWEL', '[{"wi":0,"li":0},{"wi":3,"li":1}]', 'house', 'approved'),
  (1205, 'IDIOMS', 'THE LAST STRAW', '[{"wi":1,"li":1},{"wi":2,"li":0}]', 'house', 'approved'),
  (1206, 'IDIOMS', 'OUT OF THE FRYING PAN', '[{"wi":0,"li":1},{"wi":3,"li":0}]', 'house', 'approved'),
  (1207, 'IDIOMS', 'KILL TWO BIRDS WITH ONE STONE', '[{"wi":2,"li":0},{"wi":5,"li":1}]', 'house', 'approved'),
  (1208, 'IDIOMS', 'THE BEST OF BOTH WORLDS', '[{"wi":1,"li":1},{"wi":4,"li":0}]', 'house', 'approved'),
  (1209, 'IDIOMS', 'RAINING CATS AND DOGS', '[{"wi":0,"li":0},{"wi":1,"li":1}]', 'house', 'approved'),
  (1210, 'MOTIVATIONAL', 'JUST DO IT', '[{"wi":0,"li":0},{"wi":1,"li":0}]', 'house', 'approved'),
  (1211, 'MOTIVATIONAL', 'BELIEVE IN YOURSELF', '[{"wi":0,"li":1},{"wi":2,"li":0}]', 'house', 'approved'),
  (1212, 'MOTIVATIONAL', 'DREAM BIG WORK HARD', '[{"wi":0,"li":0},{"wi":2,"li":1}]', 'house', 'approved'),
  (1213, 'MOTIVATIONAL', 'STAY HUNGRY STAY FOOLISH', '[{"wi":1,"li":1},{"wi":3,"li":0}]', 'house', 'approved'),
  (1214, 'MOTIVATIONAL', 'MAKE IT HAPPEN', '[{"wi":0,"li":1},{"wi":2,"li":0}]', 'house', 'approved'),
  (1215, 'MOTIVATIONAL', 'ONE DAY AT TIME', '[{"wi":0,"li":1},{"wi":3,"li":0}]', 'house', 'approved'),
  (1216, 'MOTIVATIONAL', 'PROGRESS NOT PERFECTION', '[{"wi":0,"li":1},{"wi":2,"li":0}]', 'house', 'approved'),
  (1217, 'MOTIVATIONAL', 'THE ONLY WAY OUT IS THROUGH', '[{"wi":1,"li":1},{"wi":5,"li":0}]', 'house', 'approved'),
  (1218, 'MOTIVATIONAL', 'FALL SEVEN TIMES STAND UP EIGHT', '[{"wi":1,"li":0},{"wi":2,"li":1}]', 'house', 'approved'),
  (1219, 'MOTIVATIONAL', 'DONE IS BETTER THAN PERFECT', '[{"wi":2,"li":1},{"wi":4,"li":0}]', 'house', 'approved'),
  (1220, 'MOTIVATIONAL', 'TRUST THE PROCESS', '[{"wi":0,"li":1},{"wi":2,"li":0}]', 'house', 'approved'),
  (1221, 'MOTIVATIONAL', 'SHOW UP EVERY DAY', '[{"wi":0,"li":1},{"wi":2,"li":0}]', 'house', 'approved'),
  (1222, 'MOTIVATIONAL', 'START WHERE YOU ARE', '[{"wi":0,"li":0},{"wi":1,"li":1}]', 'house', 'approved'),
  (1223, 'MOTIVATIONAL', 'EMBRACE THE GRIND', '[{"wi":0,"li":0},{"wi":2,"li":1}]', 'house', 'approved'),
  (1224, 'MOTIVATIONAL', 'BE THE CHANGE', '[{"wi":1,"li":1},{"wi":2,"li":0}]', 'house', 'approved'),
  (1225, 'MOTIVATIONAL', 'KEEP MOVING FORWARD', '[{"wi":1,"li":1},{"wi":2,"li":0}]', 'house', 'approved'),
  (1226, 'MOTIVATIONAL', 'YOUR ONLY LIMIT IS YOU', '[{"wi":0,"li":1},{"wi":2,"li":0}]', 'house', 'approved'),
  (1227, 'MOTIVATIONAL', 'SMALL STEPS EVERY DAY', '[{"wi":0,"li":0},{"wi":1,"li":1}]', 'house', 'approved'),
  (1228, 'MOTIVATIONAL', 'NO EXCUSES', '[{"wi":0,"li":0},{"wi":1,"li":0}]', 'house', 'approved'),
  (1229, 'MOTIVATIONAL', 'DO IT SCARED', '[{"wi":0,"li":0},{"wi":2,"li":0}]', 'house', 'approved'),
  (1230, 'FAIRY TALES', 'ONCE UPON TIME', '[{"wi":0,"li":0},{"wi":1,"li":1}]', 'house', 'approved'),
  (1231, 'FAIRY TALES', 'LITTLE RED RIDING HOOD', '[{"wi":0,"li":0},{"wi":2,"li":1}]', 'house', 'approved'),
  (1232, 'FAIRY TALES', 'JACK AND THE BEANSTALK', '[{"wi":0,"li":1},{"wi":3,"li":0}]', 'house', 'approved'),
  (1233, 'FAIRY TALES', 'THE THREE LITTLE PIGS', '[{"wi":1,"li":1},{"wi":2,"li":0}]', 'house', 'approved'),
  (1234, 'FAIRY TALES', 'SLEEPING BEAUTY', '[{"wi":0,"li":0},{"wi":1,"li":1}]', 'house', 'approved'),
  (1235, 'FAIRY TALES', 'THE UGLY DUCKLING', '[{"wi":1,"li":1},{"wi":2,"li":0}]', 'house', 'approved'),
  (1236, 'FAIRY TALES', 'HANSEL AND GRETEL', '[{"wi":0,"li":0},{"wi":2,"li":1}]', 'house', 'approved'),
  (1237, 'FAIRY TALES', 'THE FROG PRINCE', '[{"wi":1,"li":1},{"wi":2,"li":0}]', 'house', 'approved'),
  (1238, 'FAIRY TALES', 'SNOW WHITE', '[{"wi":0,"li":1},{"wi":1,"li":0}]', 'house', 'approved'),
  (1239, 'FAIRY TALES', 'THE SNOW QUEEN', '[{"wi":1,"li":1},{"wi":2,"li":0}]', 'house', 'approved'),
  (1240, 'FAIRY TALES', 'THE PRINCESS AND THE PEA', '[{"wi":0,"li":1},{"wi":1,"li":0}]', 'house', 'approved'),
  (1241, 'FAIRY TALES', 'THE EMPERORS NEW CLOTHES', '[{"wi":1,"li":0},{"wi":3,"li":1}]', 'house', 'approved'),
  (1242, 'FAIRY TALES', 'BEAUTY AND THE BEAST', '[{"wi":0,"li":0},{"wi":3,"li":1}]', 'house', 'approved'),
  (1243, 'FAIRY TALES', 'THE LITTLE MERMAID', '[{"wi":1,"li":1},{"wi":2,"li":0}]', 'house', 'approved'),
  (1244, 'FAIRY TALES', 'GOLDILOCKS AND THE THREE BEARS', '[{"wi":0,"li":0},{"wi":3,"li":1}]', 'house', 'approved'),
  (1245, 'FAIRY TALES', 'THE PIED PIPER', '[{"wi":1,"li":1},{"wi":2,"li":0}]', 'house', 'approved'),
  (1246, 'FAIRY TALES', 'MIRROR MIRROR ON THE WALL', '[{"wi":0,"li":0},{"wi":1,"li":1}]', 'house', 'approved'),
  (1247, 'FAIRY TALES', 'THE BIG BAD WOLF', '[{"wi":0,"li":1},{"wi":3,"li":0}]', 'house', 'approved'),
  (1248, 'FAIRY TALES', 'THE ELVES AND THE SHOEMAKER', '[{"wi":1,"li":1},{"wi":4,"li":0}]', 'house', 'approved'),
  (1249, 'FAIRY TALES', 'PUSS IN BOOTS', '[{"wi":0,"li":1},{"wi":2,"li":0}]', 'house', 'approved'),
  (1250, 'NURSERY RHYMES', 'TWINKLE TWINKLE LITTLE STAR', '[{"wi":0,"li":0},{"wi":1,"li":1}]', 'house', 'approved'),
  (1251, 'NURSERY RHYMES', 'HUMPTY DUMPTY SAT ON WALL', '[{"wi":0,"li":0},{"wi":1,"li":1}]', 'house', 'approved'),
  (1252, 'NURSERY RHYMES', 'JACK AND JILL WENT UP THE HILL', '[{"wi":0,"li":0},{"wi":2,"li":1}]', 'house', 'approved'),
  (1253, 'NURSERY RHYMES', 'MARY HAD LITTLE LAMB', '[{"wi":0,"li":1},{"wi":2,"li":0}]', 'house', 'approved'),
  (1254, 'NURSERY RHYMES', 'ROW ROW ROW YOUR BOAT', '[{"wi":3,"li":0},{"wi":4,"li":1}]', 'house', 'approved'),
  (1255, 'NURSERY RHYMES', 'HICKORY DICKORY DOCK', '[{"wi":0,"li":0},{"wi":1,"li":1}]', 'house', 'approved'),
  (1256, 'NURSERY RHYMES', 'THE ITSY BITSY SPIDER', '[{"wi":2,"li":1},{"wi":3,"li":0}]', 'house', 'approved'),
  (1257, 'NURSERY RHYMES', 'OLD MACDONALD HAD FARM', '[{"wi":1,"li":0},{"wi":3,"li":1}]', 'house', 'approved'),
  (1258, 'NURSERY RHYMES', 'THREE BLIND MICE', '[{"wi":0,"li":0},{"wi":1,"li":1}]', 'house', 'approved'),
  (1259, 'NURSERY RHYMES', 'LONDON BRIDGE IS FALLING DOWN', '[{"wi":0,"li":1},{"wi":3,"li":0}]', 'house', 'approved'),
  (1260, 'NURSERY RHYMES', 'HEY DIDDLE DIDDLE', '[{"wi":1,"li":0},{"wi":2,"li":1}]', 'house', 'approved'),
  (1261, 'NURSERY RHYMES', 'LITTLE MISS MUFFET', '[{"wi":0,"li":0},{"wi":2,"li":1}]', 'house', 'approved'),
  (1262, 'NURSERY RHYMES', 'BAA BAA BLACK SHEEP', '[{"wi":2,"li":0},{"wi":3,"li":1}]', 'house', 'approved'),
  (1263, 'NURSERY RHYMES', 'RING AROUND THE ROSIE', '[{"wi":1,"li":0},{"wi":3,"li":1}]', 'house', 'approved'),
  (1264, 'NURSERY RHYMES', 'THIS LITTLE PIGGY WENT TO MARKET', '[{"wi":1,"li":0},{"wi":5,"li":1}]', 'house', 'approved'),
  (1265, 'NURSERY RHYMES', 'THE WHEELS ON THE BUS', '[{"wi":0,"li":1},{"wi":1,"li":0}]', 'house', 'approved'),
  (1266, 'NURSERY RHYMES', 'RAIN RAIN GO AWAY', '[{"wi":0,"li":0},{"wi":1,"li":1}]', 'house', 'approved'),
  (1267, 'NURSERY RHYMES', 'PAT CAKE PAT CAKE', '[{"wi":1,"li":0},{"wi":3,"li":1}]', 'house', 'approved'),
  (1268, 'LANDMARKS', 'THE EIFFEL TOWER', '[{"wi":1,"li":0},{"wi":2,"li":1}]', 'house', 'approved'),
  (1269, 'LANDMARKS', 'THE GREAT WALL OF CHINA', '[{"wi":1,"li":0},{"wi":4,"li":1}]', 'house', 'approved'),
  (1270, 'LANDMARKS', 'THE STATUE OF LIBERTY', '[{"wi":1,"li":1},{"wi":3,"li":0}]', 'house', 'approved'),
  (1271, 'LANDMARKS', 'THE TAJ MAHAL', '[{"wi":0,"li":1},{"wi":2,"li":0}]', 'house', 'approved'),
  (1272, 'LANDMARKS', 'MACHU PICCHU', '[{"wi":0,"li":1},{"wi":1,"li":0}]', 'house', 'approved'),
  (1273, 'LANDMARKS', 'THE GRAND CANYON', '[{"wi":1,"li":1},{"wi":2,"li":0}]', 'house', 'approved'),
  (1274, 'LANDMARKS', 'BIG BEN', '[{"wi":0,"li":0},{"wi":1,"li":1}]', 'house', 'approved'),
  (1275, 'LANDMARKS', 'THE GOLDEN GATE BRIDGE', '[{"wi":1,"li":0},{"wi":3,"li":1}]', 'house', 'approved'),
  (1276, 'LANDMARKS', 'THE PYRAMIDS OF GIZA', '[{"wi":1,"li":0},{"wi":3,"li":1}]', 'house', 'approved'),
  (1277, 'LANDMARKS', 'THE LEANING TOWER OF PISA', '[{"wi":1,"li":0},{"wi":2,"li":1}]', 'house', 'approved'),
  (1278, 'LANDMARKS', 'THE EMPIRE STATE BUILDING', '[{"wi":1,"li":1},{"wi":3,"li":0}]', 'house', 'approved'),
  (1279, 'LANDMARKS', 'THE SYDNEY OPERA HOUSE', '[{"wi":1,"li":0},{"wi":2,"li":1}]', 'house', 'approved'),
  (1280, 'LANDMARKS', 'MOUNT RUSHMORE', '[{"wi":0,"li":1},{"wi":1,"li":0}]', 'house', 'approved'),
  (1281, 'LANDMARKS', 'THE COLOSSEUM', '[{"wi":0,"li":1},{"wi":1,"li":0}]', 'house', 'approved'),
  (1282, 'LANDMARKS', 'CHRIST THE REDEEMER', '[{"wi":0,"li":1},{"wi":2,"li":0}]', 'house', 'approved'),
  (1283, 'LANDMARKS', 'THE LOUVRE', '[{"wi":0,"li":1},{"wi":1,"li":0}]', 'house', 'approved'),
  (1284, 'LANDMARKS', 'TIMES SQUARE', '[{"wi":0,"li":1},{"wi":1,"li":0}]', 'house', 'approved'),
  (1285, 'LANDMARKS', 'NIAGARA FALLS', '[{"wi":0,"li":0},{"wi":1,"li":1}]', 'house', 'approved'),
  (1286, 'LANDMARKS', 'THE ACROPOLIS', '[{"wi":0,"li":1},{"wi":1,"li":0}]', 'house', 'approved'),
  (1287, 'LANDMARKS', 'ANGKOR WAT', '[{"wi":0,"li":0},{"wi":1,"li":1}]', 'house', 'approved'),
  (1288, 'LANDMARKS', 'BUCKINGHAM PALACE', '[{"wi":0,"li":0},{"wi":1,"li":1}]', 'house', 'approved'),
  (1289, 'LANDMARKS', 'THE HOLLYWOOD SIGN', '[{"wi":1,"li":0},{"wi":2,"li":1}]', 'house', 'approved'),
  (1290, 'FOOD AND DRINK', 'PEANUT BUTTER AND JELLY', '[{"wi":0,"li":0},{"wi":1,"li":1}]', 'house', 'approved'),
  (1291, 'FOOD AND DRINK', 'FISH AND CHIPS', '[{"wi":0,"li":1},{"wi":2,"li":0}]', 'house', 'approved'),
  (1292, 'FOOD AND DRINK', 'MACARONI AND CHEESE', '[{"wi":0,"li":0},{"wi":2,"li":1}]', 'house', 'approved'),
  (1293, 'FOOD AND DRINK', 'SPAGHETTI AND MEATBALLS', '[{"wi":0,"li":0},{"wi":2,"li":1}]', 'house', 'approved'),
  (1294, 'FOOD AND DRINK', 'CHICKEN NOODLE SOUP', '[{"wi":0,"li":0},{"wi":1,"li":1}]', 'house', 'approved'),
  (1295, 'FOOD AND DRINK', 'BACON AND EGGS', '[{"wi":0,"li":0},{"wi":2,"li":1}]', 'house', 'approved'),
  (1296, 'FOOD AND DRINK', 'GRILLED CHEESE SANDWICH', '[{"wi":0,"li":1},{"wi":2,"li":0}]', 'house', 'approved'),
  (1297, 'FOOD AND DRINK', 'CHOCOLATE CHIP COOKIES', '[{"wi":0,"li":0},{"wi":2,"li":1}]', 'house', 'approved'),
  (1298, 'FOOD AND DRINK', 'APPLE PIE', '[{"wi":0,"li":0},{"wi":1,"li":1}]', 'house', 'approved'),
  (1299, 'FOOD AND DRINK', 'BUFFALO WINGS', '[{"wi":0,"li":0},{"wi":1,"li":1}]', 'house', 'approved'),
  (1300, 'FOOD AND DRINK', 'ICE CREAM SUNDAE', '[{"wi":1,"li":1},{"wi":2,"li":0}]', 'house', 'approved'),
  (1301, 'FOOD AND DRINK', 'TOMATO SOUP', '[{"wi":0,"li":0},{"wi":1,"li":1}]', 'house', 'approved'),
  (1302, 'FOOD AND DRINK', 'PANCAKES AND SYRUP', '[{"wi":0,"li":0},{"wi":2,"li":1}]', 'house', 'approved'),
  (1303, 'FOOD AND DRINK', 'SALT AND VINEGAR', '[{"wi":0,"li":1},{"wi":2,"li":0}]', 'house', 'approved'),
  (1304, 'FOOD AND DRINK', 'PUMPKIN SPICE LATTE', '[{"wi":0,"li":0},{"wi":1,"li":1}]', 'house', 'approved'),
  (1305, 'FOOD AND DRINK', 'SURF AND TURF', '[{"wi":0,"li":0},{"wi":2,"li":1}]', 'house', 'approved'),
  (1306, 'FOOD AND DRINK', 'PEPPERONI PIZZA', '[{"wi":0,"li":0},{"wi":1,"li":1}]', 'house', 'approved'),
  (1307, 'FOOD AND DRINK', 'FRENCH ONION SOUP', '[{"wi":0,"li":0},{"wi":1,"li":1}]', 'house', 'approved'),
  (1308, 'FOOD AND DRINK', 'BEEF WELLINGTON', '[{"wi":0,"li":1},{"wi":1,"li":0}]', 'house', 'approved'),
  (1309, 'FOOD AND DRINK', 'STRAWBERRY SHORTCAKE', '[{"wi":0,"li":0},{"wi":1,"li":1}]', 'house', 'approved'),
  (1310, 'FOOD AND DRINK', 'CHICKEN TIKKA MASALA', '[{"wi":0,"li":0},{"wi":2,"li":1}]', 'house', 'approved'),
  (1311, 'FOOD AND DRINK', 'BREAKFAST BURRITO', '[{"wi":0,"li":0},{"wi":1,"li":1}]', 'house', 'approved'),
  (1312, 'SPORTS', 'HOME RUN', '[{"wi":0,"li":0},{"wi":1,"li":1}]', 'house', 'approved'),
  (1313, 'SPORTS', 'SLAM DUNK', '[{"wi":0,"li":0},{"wi":1,"li":1}]', 'house', 'approved'),
  (1314, 'SPORTS', 'HOLE IN ONE', '[{"wi":0,"li":0},{"wi":2,"li":1}]', 'house', 'approved'),
  (1315, 'SPORTS', 'HAT TRICK', '[{"wi":0,"li":1},{"wi":1,"li":0}]', 'house', 'approved'),
  (1316, 'SPORTS', 'TOUCHDOWN DANCE', '[{"wi":0,"li":0},{"wi":1,"li":1}]', 'house', 'approved'),
  (1317, 'SPORTS', 'GRAND SLAM', '[{"wi":0,"li":0},{"wi":1,"li":1}]', 'house', 'approved'),
  (1318, 'SPORTS', 'PHOTO FINISH', '[{"wi":0,"li":1},{"wi":1,"li":0}]', 'house', 'approved'),
  (1319, 'SPORTS', 'SUDDEN DEATH', '[{"wi":0,"li":0},{"wi":1,"li":1}]', 'house', 'approved'),
  (1320, 'SPORTS', 'THE SUPER BOWL', '[{"wi":1,"li":0},{"wi":2,"li":1}]', 'house', 'approved'),
  (1321, 'SPORTS', 'THE WORLD CUP', '[{"wi":0,"li":1},{"wi":1,"li":0}]', 'house', 'approved'),
  (1322, 'SPORTS', 'THE STANLEY CUP', '[{"wi":0,"li":1},{"wi":1,"li":0}]', 'house', 'approved'),
  (1323, 'SPORTS', 'MARCH MADNESS', '[{"wi":0,"li":1},{"wi":1,"li":0}]', 'house', 'approved'),
  (1324, 'SPORTS', 'THE TOUR DE FRANCE', '[{"wi":1,"li":1},{"wi":3,"li":0}]', 'house', 'approved'),
  (1325, 'SPORTS', 'FULL COURT PRESS', '[{"wi":1,"li":0},{"wi":2,"li":1}]', 'house', 'approved'),
  (1326, 'SPORTS', 'THE OLYMPIC GAMES', '[{"wi":1,"li":0},{"wi":2,"li":1}]', 'house', 'approved'),
  (1327, 'SPORTS', 'DOUBLE OVERTIME', '[{"wi":0,"li":1},{"wi":1,"li":0}]', 'house', 'approved'),
  (1328, 'SPORTS', 'BUZZER BEATER', '[{"wi":0,"li":0},{"wi":1,"li":1}]', 'house', 'approved'),
  (1329, 'SPORTS', 'DOWN TO THE WIRE', '[{"wi":0,"li":0},{"wi":3,"li":1}]', 'house', 'approved'),
  (1330, 'SPORTS', 'THE KENTUCKY DERBY', '[{"wi":1,"li":0},{"wi":2,"li":1}]', 'house', 'approved'),
  (1331, 'SPORTS', 'THE WORLD SERIES', '[{"wi":1,"li":1},{"wi":2,"li":0}]', 'house', 'approved'),
  (1332, 'SCIENCE', 'THE THEORY OF RELATIVITY', '[{"wi":1,"li":1},{"wi":3,"li":0}]', 'house', 'approved'),
  (1333, 'SCIENCE', 'THE SPEED OF LIGHT', '[{"wi":1,"li":0},{"wi":3,"li":1}]', 'house', 'approved'),
  (1334, 'SCIENCE', 'NATURAL SELECTION', '[{"wi":0,"li":1},{"wi":1,"li":0}]', 'house', 'approved'),
  (1335, 'SCIENCE', 'THE BIG BANG', '[{"wi":0,"li":1},{"wi":2,"li":0}]', 'house', 'approved'),
  (1336, 'SCIENCE', 'THE PERIODIC TABLE', '[{"wi":1,"li":0},{"wi":2,"li":1}]', 'house', 'approved'),
  (1337, 'SCIENCE', 'THE LAW OF GRAVITY', '[{"wi":0,"li":1},{"wi":3,"li":0}]', 'house', 'approved'),
  (1338, 'SCIENCE', 'PLATE TECTONICS', '[{"wi":0,"li":1},{"wi":1,"li":0}]', 'house', 'approved'),
  (1339, 'SCIENCE', 'THE DOUBLE HELIX', '[{"wi":1,"li":0},{"wi":2,"li":1}]', 'house', 'approved'),
  (1340, 'SCIENCE', 'BLACK HOLE', '[{"wi":0,"li":0},{"wi":1,"li":1}]', 'house', 'approved'),
  (1341, 'SCIENCE', 'THE WATER CYCLE', '[{"wi":1,"li":0},{"wi":2,"li":1}]', 'house', 'approved'),
  (1342, 'SCIENCE', 'NEWTONS THIRD LAW', '[{"wi":0,"li":0},{"wi":1,"li":1}]', 'house', 'approved'),
  (1343, 'SCIENCE', 'THE SCIENTIFIC METHOD', '[{"wi":1,"li":0},{"wi":2,"li":1}]', 'house', 'approved'),
  (1344, 'SCIENCE', 'THE SPEED OF SOUND', '[{"wi":1,"li":0},{"wi":3,"li":1}]', 'house', 'approved'),
  (1345, 'SCIENCE', 'QUANTUM MECHANICS', '[{"wi":0,"li":1},{"wi":1,"li":0}]', 'house', 'approved'),
  (1346, 'SCIENCE', 'THE FOOD CHAIN', '[{"wi":1,"li":1},{"wi":2,"li":0}]', 'house', 'approved'),
  (1347, 'SCIENCE', 'SURVIVAL OF THE FITTEST', '[{"wi":0,"li":0},{"wi":3,"li":1}]', 'house', 'approved'),
  (1348, 'SCIENCE', 'THE GREENHOUSE EFFECT', '[{"wi":1,"li":0},{"wi":2,"li":1}]', 'house', 'approved'),
  (1349, 'SCIENCE', 'ABSOLUTE ZERO', '[{"wi":0,"li":0},{"wi":1,"li":1}]', 'house', 'approved'),
  (1350, 'SCIENCE', 'THE MILKY WAY', '[{"wi":0,"li":1},{"wi":1,"li":0}]', 'house', 'approved'),
  (1351, 'SCIENCE', 'CHAIN REACTION', '[{"wi":0,"li":1},{"wi":1,"li":0}]', 'house', 'approved'),
  (1352, 'ANIMALS', 'GREAT WHITE SHARK', '[{"wi":0,"li":0},{"wi":1,"li":1}]', 'house', 'approved'),
  (1353, 'ANIMALS', 'BALD EAGLE', '[{"wi":0,"li":1},{"wi":1,"li":0}]', 'house', 'approved'),
  (1354, 'ANIMALS', 'GOLDEN RETRIEVER', '[{"wi":0,"li":1},{"wi":1,"li":0}]', 'house', 'approved'),
  (1355, 'ANIMALS', 'POLAR BEAR', '[{"wi":0,"li":0},{"wi":1,"li":1}]', 'house', 'approved'),
  (1356, 'ANIMALS', 'BLUE WHALE', '[{"wi":0,"li":1},{"wi":1,"li":0}]', 'house', 'approved'),
  (1357, 'ANIMALS', 'KING COBRA', '[{"wi":0,"li":1},{"wi":1,"li":0}]', 'house', 'approved'),
  (1358, 'ANIMALS', 'EMPEROR PENGUIN', '[{"wi":0,"li":0},{"wi":1,"li":1}]', 'house', 'approved'),
  (1359, 'ANIMALS', 'MOUNTAIN GORILLA', '[{"wi":0,"li":0},{"wi":1,"li":1}]', 'house', 'approved'),
  (1360, 'ANIMALS', 'SNOW LEOPARD', '[{"wi":0,"li":1},{"wi":1,"li":0}]', 'house', 'approved'),
  (1361, 'ANIMALS', 'GIANT PANDA', '[{"wi":0,"li":0},{"wi":1,"li":1}]', 'house', 'approved'),
  (1362, 'ANIMALS', 'HONEY BADGER', '[{"wi":0,"li":1},{"wi":1,"li":0}]', 'house', 'approved'),
  (1363, 'ANIMALS', 'MONARCH BUTTERFLY', '[{"wi":0,"li":1},{"wi":1,"li":0}]', 'house', 'approved'),
  (1364, 'ANIMALS', 'KOMODO DRAGON', '[{"wi":0,"li":0},{"wi":1,"li":1}]', 'house', 'approved'),
  (1365, 'ANIMALS', 'BENGAL TIGER', '[{"wi":0,"li":0},{"wi":1,"li":1}]', 'house', 'approved'),
  (1366, 'ANIMALS', 'HUMPBACK WHALE', '[{"wi":0,"li":0},{"wi":1,"li":1}]', 'house', 'approved'),
  (1367, 'ANIMALS', 'RED PANDA', '[{"wi":0,"li":1},{"wi":1,"li":0}]', 'house', 'approved'),
  (1368, 'ANIMALS', 'GRIZZLY BEAR', '[{"wi":0,"li":0},{"wi":1,"li":1}]', 'house', 'approved'),
  (1369, 'ANIMALS', 'BOTTLENOSE DOLPHIN', '[{"wi":0,"li":0},{"wi":1,"li":1}]', 'house', 'approved'),
  (1370, 'ANIMALS', 'BLACK WIDOW SPIDER', '[{"wi":0,"li":1},{"wi":2,"li":0}]', 'house', 'approved'),
  (1371, 'ANIMALS', 'SIBERIAN HUSKY', '[{"wi":0,"li":0},{"wi":1,"li":1}]', 'house', 'approved'),
  (1372, 'HOLIDAYS', 'HAPPY NEW YEAR', '[{"wi":0,"li":0},{"wi":2,"li":1}]', 'house', 'approved'),
  (1373, 'HOLIDAYS', 'MERRY CHRISTMAS', '[{"wi":0,"li":1},{"wi":1,"li":0}]', 'house', 'approved'),
  (1374, 'HOLIDAYS', 'TRICK OR TREAT', '[{"wi":0,"li":0},{"wi":2,"li":1}]', 'house', 'approved'),
  (1375, 'HOLIDAYS', 'HAPPY BIRTHDAY TO YOU', '[{"wi":0,"li":1},{"wi":1,"li":0}]', 'house', 'approved'),
  (1376, 'HOLIDAYS', 'FOURTH OF JULY', '[{"wi":0,"li":0},{"wi":2,"li":1}]', 'house', 'approved'),
  (1377, 'HOLIDAYS', 'BLACK FRIDAY', '[{"wi":0,"li":1},{"wi":1,"li":0}]', 'house', 'approved'),
  (1378, 'HOLIDAYS', 'VALENTINES DAY', '[{"wi":0,"li":0},{"wi":1,"li":1}]', 'house', 'approved'),
  (1379, 'HOLIDAYS', 'NEW YEARS EVE', '[{"wi":0,"li":1},{"wi":1,"li":0}]', 'house', 'approved'),
  (1380, 'HOLIDAYS', 'THE TWELVE DAYS OF CHRISTMAS', '[{"wi":1,"li":1},{"wi":4,"li":0}]', 'house', 'approved'),
  (1381, 'HOLIDAYS', 'HAPPY HALLOWEEN', '[{"wi":0,"li":1},{"wi":1,"li":0}]', 'house', 'approved'),
  (1382, 'HOLIDAYS', 'MOTHERS DAY', '[{"wi":0,"li":0},{"wi":1,"li":1}]', 'house', 'approved'),
  (1383, 'HOLIDAYS', 'FATHERS DAY', '[{"wi":0,"li":0},{"wi":1,"li":1}]', 'house', 'approved'),
  (1384, 'HOLIDAYS', 'MARDI GRAS', '[{"wi":0,"li":0},{"wi":1,"li":1}]', 'house', 'approved'),
  (1385, 'HOLIDAYS', 'SAINT PATRICKS DAY', '[{"wi":0,"li":1},{"wi":1,"li":0}]', 'house', 'approved'),
  (1386, 'HOLIDAYS', 'AULD LANG SYNE', '[{"wi":0,"li":0},{"wi":1,"li":1}]', 'house', 'approved'),
  (1387, 'HOLIDAYS', 'JINGLE ALL THE WAY', '[{"wi":0,"li":0},{"wi":1,"li":1}]', 'house', 'approved'),
  (1388, 'HOLIDAYS', 'EASTER EGG HUNT', '[{"wi":0,"li":0},{"wi":2,"li":1}]', 'house', 'approved'),
  (1389, 'HOLIDAYS', 'LABOR DAY WEEKEND', '[{"wi":0,"li":1},{"wi":2,"li":0}]', 'house', 'approved'),
  (1390, 'FAMOUS SPEECHES', 'HAVE DREAM', '[{"wi":0,"li":1},{"wi":1,"li":0}]', 'house', 'approved'),
  (1391, 'FAMOUS SPEECHES', 'ASK NOT WHAT YOUR COUNTRY CAN DO', '[{"wi":2,"li":1},{"wi":4,"li":0}]', 'house', 'approved'),
  (1392, 'FAMOUS SPEECHES', 'WE SHALL FIGHT ON THE BEACHES', '[{"wi":1,"li":1},{"wi":5,"li":0}]', 'house', 'approved'),
  (1393, 'FAMOUS SPEECHES', 'THE ONLY THING WE HAVE TO FEAR', '[{"wi":1,"li":1},{"wi":2,"li":0}]', 'house', 'approved'),
  (1394, 'FAMOUS SPEECHES', 'TEAR DOWN THIS WALL', '[{"wi":0,"li":0},{"wi":1,"li":1}]', 'house', 'approved'),
  (1395, 'FAMOUS SPEECHES', 'GIVE ME LIBERTY OR GIVE ME DEATH', '[{"wi":2,"li":0},{"wi":6,"li":1}]', 'house', 'approved'),
  (1396, 'FAMOUS SPEECHES', 'BLOOD TOIL TEARS AND SWEAT', '[{"wi":0,"li":0},{"wi":2,"li":1}]', 'house', 'approved'),
  (1397, 'FAMOUS SPEECHES', 'ONE SMALL STEP FOR MAN', '[{"wi":1,"li":0},{"wi":2,"li":1}]', 'house', 'approved'),
  (1398, 'FAMOUS SPEECHES', 'WE CHOOSE TO GO TO THE MOON', '[{"wi":1,"li":0},{"wi":6,"li":1}]', 'house', 'approved'),
  (1399, 'FAMOUS SPEECHES', 'THE BALLOT OR THE BULLET', '[{"wi":1,"li":0},{"wi":4,"li":1}]', 'house', 'approved'),
  (1400, 'FAMOUS SPEECHES', 'YES WE CAN', '[{"wi":0,"li":0},{"wi":2,"li":1}]', 'house', 'approved'),
  (1401, 'FAMOUS SPEECHES', 'NEVER GIVE IN', '[{"wi":0,"li":0},{"wi":1,"li":1}]', 'house', 'approved'),
  (1402, 'FAMOUS SPEECHES', 'GOVERNMENT OF THE PEOPLE', '[{"wi":0,"li":0},{"wi":3,"li":1}]', 'house', 'approved'),
  (1403, 'FAMOUS SPEECHES', 'LET FREEDOM RING', '[{"wi":1,"li":0},{"wi":2,"li":1}]', 'house', 'approved'),
  (1404, 'FAMOUS SPEECHES', 'THIS WAS THEIR FINEST HOUR', '[{"wi":2,"li":1},{"wi":3,"li":0}]', 'house', 'approved'),
  (1405, 'CARPE DIEM', 'LIVE IN THE MOMENT', '[{"wi":0,"li":1},{"wi":3,"li":0}]', 'house', 'approved'),
  (1406, 'CARPE DIEM', 'LIFE IS SHORT', '[{"wi":0,"li":1},{"wi":2,"li":0}]', 'house', 'approved'),
  (1407, 'CARPE DIEM', 'TOMORROW IS NOT PROMISED', '[{"wi":0,"li":0},{"wi":3,"li":1}]', 'house', 'approved'),
  (1408, 'CARPE DIEM', 'MAKE EVERY DAY COUNT', '[{"wi":1,"li":0},{"wi":3,"li":1}]', 'house', 'approved'),
  (1409, 'CARPE DIEM', 'NO TIME LIKE THE PRESENT', '[{"wi":1,"li":1},{"wi":4,"li":0}]', 'house', 'approved'),
  (1410, 'CARPE DIEM', 'GATHER YE ROSEBUDS', '[{"wi":0,"li":1},{"wi":2,"li":0}]', 'house', 'approved'),
  (1411, 'CARPE DIEM', 'YOU ONLY LIVE ONCE', '[{"wi":1,"li":0},{"wi":2,"li":1}]', 'house', 'approved'),
  (1412, 'CARPE DIEM', 'TAKE THE LEAP', '[{"wi":0,"li":0},{"wi":2,"li":1}]', 'house', 'approved'),
  (1413, 'CARPE DIEM', 'NOW OR NEVER', '[{"wi":0,"li":1},{"wi":2,"li":0}]', 'house', 'approved'),
  (1414, 'CARPE DIEM', 'LIVE LIKE THERE IS NO TOMORROW', '[{"wi":2,"li":1},{"wi":5,"li":0}]', 'house', 'approved'),
  (1415, 'CARPE DIEM', 'THE TIME IS NOW', '[{"wi":0,"li":1},{"wi":1,"li":0}]', 'house', 'approved'),
  (1416, 'CARPE DIEM', 'DONT WAIT FOR PERFECT', '[{"wi":0,"li":1},{"wi":3,"li":0}]', 'house', 'approved'),
  (1417, 'CARPE DIEM', 'LIFE BEGINS AT THE END OF COMFORT', '[{"wi":1,"li":1},{"wi":6,"li":0}]', 'house', 'approved'),
  (1418, 'CARPE DIEM', 'EVERY MOMENT MATTERS', '[{"wi":1,"li":1},{"wi":2,"li":0}]', 'house', 'approved'),
  (1419, 'CARPE DIEM', 'BE HERE NOW', '[{"wi":1,"li":0},{"wi":2,"li":1}]', 'house', 'approved');
