/* Auth modal — native <dialog>, outer shell + login/register switcher
   generated by @basenative/components' renderDialog()/renderTabs(),
   with the switcher's behaviour (WAI-ARIA APG tabs pattern: click +
   ArrowLeft/ArrowRight/Home/End, aria-selected, roving tabindex) from
   its initTabs() — instead of hand-built <dialog>/<article>/<menu
   role="tablist"> markup and a local click-only tab handler. The
   <form> itself is unchanged: still built with h() because it's
   genuinely signal-driven (handle input, busy/err state, the
   passkey-vs-dev-login buttons) — none of that belongs in a pure
   string renderer. Attribute-driven visuals are unchanged too: form/
   field/input/hint/error from [data-bn-region="form|field|input|hint|
   error"] and the title accent from [data-bn-region="title"]
   [data-tone="auth"]. The buttons are renderButton() and the card that
   holds the whole thing is renderCard() — T4BS's own
   [data-bn-button="primary|secondary"] vocabulary is retired. */

import { signal, effect } from "@basenative/runtime";
import { renderButton, renderCard, renderDialog, renderTabs, initTabs } from "@basenative/components";
import { bnAlert, bnButton, h, fromHTML } from "../lib/dom.js";
import { bindDisabled, bindHidden, bindText } from "../lib/bind.js";
import { isPasskeySupported, registerPasskey, loginPasskey, devLogin } from "../lib/auth.js";
import { isDev } from "../lib/game.js";

const AUTH_TABS_ID = "auth-tabs";
const AUTH_PANEL_ID = "auth-tabs-panel";

/* Maps the raw error slugs the server / @basenative/auth-webauthn client
   throw (see its src/server.js and src/client.js) to user-facing copy —
   the modal used to show these verbatim ('user-not-found', 'auth-failed'). */
const AUTH_ERROR_COPY = {
  "user-not-found": "No account with that handle — try NEW HANDLE instead.",
  "bad-handle": "Handles are 2–24 characters: letters, numbers, _ or -.",
  "credential-not-found": "That passkey isn't recognized on this device — try NEW HANDLE.",
  "challenge-not-found": "That sign-in attempt expired — try again.",
  "bad-challenge": "That sign-in attempt expired — try again.",
  "not-verified": "Passkey verification failed — try again.",
  "missing-assertion": "Passkey verification failed — try again.",
  "missing-attestation": "Passkey verification failed — try again.",
};
const AUTH_ERROR_FALLBACK = "Sign-in failed — try again.";

function authErrorCopy(e) {
  const code = String(e?.message ?? e ?? "");
  // Browser-side WebAuthn cancellation (e.g. the OS passkey sheet was
  // dismissed) surfaces as a DOMException, not one of the server's slugs.
  if (e?.name === "NotAllowedError" || /not allowed|cancel/i.test(code)) {
    return "Passkey was cancelled.";
  }
  return AUTH_ERROR_COPY[code] || AUTH_ERROR_FALLBACK;
}

/**
 * The auth dialog's static shell — header, login/register tab
 * switcher, cancel button — as a plain string. No signals, no DOM, so
 * it's testable on its own (renderDialog/renderTabs are pure string
 * renderers). createAuthModal() below parses this once, then slots the
 * real (signal-driven) <form> into [data-bn-region="form-slot"] and
 * hands the tab switcher to initTabs().
 */
export function authDialogHtml() {
  const tabsHtml = renderTabs({
    id: AUTH_TABS_ID,
    tabs: [
      { id: "login", label: "LOG IN" },
      { id: "register", label: "NEW HANDLE" },
    ],
    activeTab: "login",
  });
  return renderDialog({
    id: "auth-dialog",
    modal: true,
    closable: false,
    /* renderCard() supplies the modal card — the surface, border,
       radius and shadow that every T4BS dialog shares — so the dialog
       element itself is left as the scrim it already was. */
    content: renderCard({
      body: `
      <!-- Plain <div>, not <header>: a <header> not nested inside an
           article/aside/main/nav/section computes as a top-level
           "banner" landmark (axe landmark-banner-is-top-level) even
           while sitting inside an open dialog. -->
      <div>
        <h2 id="auth-title" data-bn-region="title" data-tone="auth">SIGN IN</h2>
        <p data-bn-region="subtitle">Anonymous play · login only to submit</p>
      </div>
      ${tabsHtml}
      <div data-bn-region="form-slot"></div>
      ${renderButton("Cancel", { variant: "secondary", attrs: 'data-bn-action="auth-cancel"' })}
    `,
    }),
  });
}

export function createAuthModal({ open, onClose, onAuthed }) {
  const tab    = signal("login");
  const handle = signal("");
  const busy   = signal(false);
  const err    = signal(null);
  const passkey = isPasskeySupported();

  async function doIt(fn) {
    busy.set(true); err.set(null);
    try {
      const me = await fn(handle.peek().trim().toLowerCase());
      if (me?.user) onAuthed(me.user);
      else err.set(AUTH_ERROR_FALLBACK);
    } catch (e) {
      err.set(authErrorCopy(e));
    } finally {
      busy.set(false);
    }
  }

  const handleInput = h("input", {
    id: "auth-handle",
    name: "handle",
    "data-bn-region": "input",
    autocapitalize: "off",
    autocorrect: "off",
    spellcheck: "false",
    autocomplete: "username",
    placeholder: "2–24 chars · letters, numbers, _ -",
    onInput: (e) => handle.set(e.target.value),
  });

  /* The error variant of @basenative/components' alert carries
     role="alert" itself, and the message lands in its escaped text slot
     instead of being assigned as markup. */
  const errAlert = bnAlert({ variant: "error" });
  const errBox = errAlert.el;
  bindText(errAlert.content, () => err() || "");
  bindHidden(errBox, () => !err());

  const passkeyBtn = bnButton("USE PASSKEY", { variant: "primary", type: "submit" });
  bindDisabled(passkeyBtn, () => busy() || !handle());
  bindText(passkeyBtn, () => busy() ? "…" : tab() === "login" ? "USE PASSKEY" : "CREATE PASSKEY");

  const noPasskeyHint = h("p", { "data-bn-region": "hint" }, "This browser doesn't support passkeys.");

  const devBtn = bnButton("DEV LOGIN (no passkey)", {
    variant: "secondary",
    onClick: () => doIt(devLogin),
  });
  bindDisabled(devBtn, () => busy() || !handle());

  const form = h("form", {
    "data-bn-region": "form",
    onSubmit: (e) => {
      e.preventDefault();
      if (passkey && !busy() && handle()) {
        doIt(tab.peek() === "login" ? loginPasskey : registerPasskey);
      }
    },
  },
    h("p", { "data-bn-region": "field" },
      h("label", { for: "auth-handle" }, "Handle"),
      handleInput,
      h("small", { "data-bn-region": "hint" }, "Public attribution on your puzzles."),
    ),
    errBox,
    passkey ? passkeyBtn : noPasskeyHint,
  );

  const dlg = /** @type {HTMLDialogElement} */ (fromHTML(authDialogHtml()));
  /* renderDialog() emits aria-labelledby only for its own `title`
     slot; this dialog keeps its title inside the card (see
     authDialogHtml), so the label is pointed at that h2 here. */
  dlg.setAttribute("aria-labelledby", "auth-title");
  dlg.addEventListener("close", onClose);
  dlg.addEventListener("click", (e) => { if (e.target === dlg) onClose(); });
  dlg.querySelector('[data-bn-action="auth-cancel"]').addEventListener("click", onClose);

  /* renderTabs() renders one [data-bn="tab-panel"] per tab. Both tabs
     drive the SAME shared <form> here (only the submit handler + button
     label depend on which is active — same single-form design as
     before), so per-tab panels would sit permanently empty while the
     real content lives elsewhere: worse for a screen reader than no
     panel at all (an empty landmark plus a dangling aria-controls). They
     are removed, and a single shared tabpanel wrapping the real form (+
     the dev-login button) takes their place, with aria-labelledby
     following whichever tab is active — so the tablist/tabpanel
     relationship stays real instead of just decorative. */
  dlg.querySelectorAll('[data-bn="tab-panel"]').forEach((el) => el.remove());
  const loginTab    = dlg.querySelector('[data-tab="login"]');
  const registerTab = dlg.querySelector('[data-tab="register"]');
  loginTab.setAttribute("aria-controls", AUTH_PANEL_ID);
  registerTab.setAttribute("aria-controls", AUTH_PANEL_ID);

  /* initTabs() owns the switcher from here: click and ArrowLeft/
     ArrowRight/Home/End select (wrapping at the ends), and it keeps
     aria-selected + the roving tabindex in step — the APG tabs pattern
     the previous click-only handler didn't implement. onChange fires
     for user-driven changes only, so it just mirrors the selection into
     the `tab` signal (still the source of truth for the submit handler
     and button label). Its panel hiding keys off [data-bn="tab-panel"]
     elements, which were removed just above, so it's a no-op here and
     the shared tabpanel stays visible under either tab, as intended. */
  const tabs = initTabs(dlg.querySelector(`#${AUTH_TABS_ID}`), {
    onChange: (id) => tab.set(id),
  });

  const panelChildren = [form];
  if (isDev()) panelChildren.push(devBtn);
  dlg.querySelector('[data-bn-region="form-slot"]').replaceWith(h("div", {
    role: "tabpanel",
    id: AUTH_PANEL_ID,
    "aria-labelledby": () => tab() === "login" ? loginTab.id : registerTab.id,
  }, ...panelChildren));

  let lastOpen = false;
  effect(() => {
    const isOpen = open();
    if (isOpen && !lastOpen) {
      handle.set(""); err.set(null); busy.set(false); tab.set("login");
      /* select() is silent (no onChange, no focus move), so the DOM
         follows the signal reset above without echoing back into it. */
      tabs.select("login");
    }
    /* Guard `isConnected`: a signal flip that lands before this dialog
       is mounted (e.g. the /submit route bouncing a signed-out visitor
       to "/" while opening the auth prompt, before hydrate.js's
       mount() call has appended it to #app) would otherwise throw
       "showModal ... not in a Document" and abort the whole hydrate
       script before mount() ever runs. */
    if (isOpen && !dlg.open && dlg.isConnected) dlg.showModal();
    else if (!isOpen && dlg.open) dlg.close();
    lastOpen = isOpen;
  });

  return dlg;
}
