/* Auth modal — native <dialog>, outer shell + login/register switcher
   generated by @basenative/components' renderDialog()/renderTabs()
   instead of hand-built <dialog>/<article>/<menu role="tablist">
   markup. The <form> itself is unchanged: still built with h() because
   it's genuinely signal-driven (handle input, busy/err state, the
   passkey-vs-dev-login buttons) — none of that belongs in a pure
   string renderer. Attribute-driven visuals are unchanged too: form/
   field/input/hint/error from [data-bn-region="form|field|input|hint|
   error"], the title accent from [data-bn-region="title"][data-tone=
   "auth"], buttons from [data-bn-button="primary|secondary"]. */

import { signal, effect } from "@basenative/runtime";
import { renderDialog, renderTabs } from "@basenative/components";
import { h, fromHTML } from "../lib/dom.js";
import { isPasskeySupported, registerPasskey, loginPasskey, devLogin } from "../lib/auth.js";
import { isDev } from "../lib/game.js";

const AUTH_TABS_ID = "auth-tabs";
const AUTH_PANEL_ID = "auth-tabs-panel";

/**
 * The auth dialog's static shell — header, login/register tab
 * switcher, cancel button — as a plain string. No signals, no DOM, so
 * it's testable on its own (renderDialog/renderTabs are pure string
 * renderers). createAuthModal() below parses this once, then slots the
 * real (signal-driven) <form> into [data-bn-region="form-slot"] and
 * wires up the tab buttons' click/aria-selected behaviour.
 */
export function authDialogHtml() {
  const tabsHtml = renderTabs({
    id: AUTH_TABS_ID,
    tabs: [
      { id: "login", label: "LOG IN" },
      { id: "register", label: "NEW HANDLE" },
    ],
    activeTab: "login",
  });
  return renderDialog({
    id: "auth-dialog",
    modal: true,
    closable: false,
    content: `
      <header>
        <h2 id="auth-title" data-bn-region="title" data-tone="auth">SIGN IN</h2>
        <p data-bn-region="subtitle">Anonymous play · login only to submit</p>
      </header>
      ${tabsHtml}
      <div data-bn-region="form-slot"></div>
      <button type="button" data-bn-button="secondary" data-bn-action="auth-cancel">Cancel</button>
    `,
  });
}

export function createAuthModal({ open, onClose, onAuthed }) {
  const tab    = signal("login");
  const handle = signal("");
  const busy   = signal(false);
  const err    = signal(null);
  const passkey = isPasskeySupported();

  async function doIt(fn) {
    busy.set(true); err.set(null);
    try {
      const me = await fn(handle.peek().trim().toLowerCase());
      if (me?.user) onAuthed(me.user);
      else err.set("auth-failed");
    } catch (e) {
      err.set(String(e.message || e));
    } finally {
      busy.set(false);
    }
  }

  const handleInput = h("input", {
    id: "auth-handle",
    name: "handle",
    "data-bn-region": "input",
    autocapitalize: "off",
    autocorrect: "off",
    spellcheck: "false",
    autocomplete: "username",
    placeholder: "2–24 chars · letters, numbers, _ -",
    onInput: (e) => handle.set(e.target.value),
  });

  const errBox = h("p", {
    "data-bn-region": "error",
    role: "alert",
    text: () => err() || "",
    hidden: () => !err(),
  });

  const passkeyBtn = h("button", {
    type: "submit",
    "data-bn-button": "primary",
    disabled: () => busy() || !handle(),
    text: () => busy() ? "…" : tab() === "login" ? "USE PASSKEY" : "CREATE PASSKEY",
  });

  const noPasskeyHint = h("p", { "data-bn-region": "hint" }, "This browser doesn't support passkeys.");

  const devBtn = h("button", {
    type: "button",
    "data-bn-button": "secondary",
    disabled: () => busy() || !handle(),
    onClick: () => doIt(devLogin),
  }, "DEV LOGIN (no passkey)");

  const form = h("form", {
    "data-bn-region": "form",
    onSubmit: (e) => {
      e.preventDefault();
      if (passkey && !busy() && handle()) {
        doIt(tab.peek() === "login" ? loginPasskey : registerPasskey);
      }
    },
  },
    h("p", { "data-bn-region": "field" },
      h("label", { for: "auth-handle" }, "Handle"),
      handleInput,
      h("small", { "data-bn-region": "hint" }, "Public attribution on your puzzles."),
    ),
    errBox,
    passkey ? passkeyBtn : noPasskeyHint,
  );

  const dlg = /** @type {HTMLDialogElement} */ (fromHTML(authDialogHtml()));
  dlg.setAttribute("aria-labelledby", "auth-title");
  dlg.addEventListener("close", onClose);
  dlg.addEventListener("click", (e) => { if (e.target === dlg) onClose(); });
  dlg.querySelector('[data-bn-action="auth-cancel"]').addEventListener("click", onClose);

  /* renderTabs() renders one [data-bn="tab-panel"] per tab. Both tabs
     drive the SAME shared <form> here (only the submit handler + button
     label depend on which is active — same single-form design as
     before), so per-tab panels would sit permanently empty while the
     real content lives elsewhere: worse for a screen reader than no
     panel at all (an empty landmark plus a dangling aria-controls). They
     are removed, and a single shared tabpanel wrapping the real form (+
     the dev-login button) takes their place, with aria-labelledby
     following whichever tab is active — so the tablist/tabpanel
     relationship stays real instead of just decorative. */
  dlg.querySelectorAll('[data-bn="tab-panel"]').forEach((el) => el.remove());
  const loginTab    = dlg.querySelector('[data-tab="login"]');
  const registerTab = dlg.querySelector('[data-tab="register"]');
  loginTab.setAttribute("aria-controls", AUTH_PANEL_ID);
  registerTab.setAttribute("aria-controls", AUTH_PANEL_ID);
  loginTab.addEventListener("click", () => tab.set("login"));
  registerTab.addEventListener("click", () => tab.set("register"));
  effect(() => {
    const active = tab();
    loginTab.setAttribute("aria-selected", String(active === "login"));
    registerTab.setAttribute("aria-selected", String(active === "register"));
  });

  const panelChildren = [form];
  if (isDev()) panelChildren.push(devBtn);
  dlg.querySelector('[data-bn-region="form-slot"]').replaceWith(h("div", {
    role: "tabpanel",
    id: AUTH_PANEL_ID,
    "aria-labelledby": () => tab() === "login" ? loginTab.id : registerTab.id,
  }, ...panelChildren));

  let lastOpen = false;
  effect(() => {
    const isOpen = open();
    if (isOpen && !lastOpen) {
      handle.set(""); err.set(null); busy.set(false); tab.set("login");
    }
    if (isOpen && !dlg.open) dlg.showModal();
    else if (!isOpen && dlg.open) dlg.close();
    lastOpen = isOpen;
  });

  return dlg;
}
