/* How-to-play — native <dialog>, markup generated by
   @basenative/components' renderDialog() for the outer shell
   ([data-bn="dialog"]'s card chrome: border-radius, background,
   box-shadow, max-width — see components.css) instead of a hand-built
   <dialog>/<article> pair. The inner content is unchanged: the title
   accent from [data-bn-region="title"][data-tone="help"], the body
   from [data-bn-region="help-body"], and the close button from
   [data-bn-button="primary"] — all still T4BS's own attribute-driven
   CSS, passed to renderDialog()'s `content` slot as-is (not the
   `title`/`footer` slots) so the layout doesn't shift: this dialog has
   no dynamic content, so there's nothing signal-driven to lose by
   building the whole thing as one string. */

import { effect } from "@basenative/runtime";
import { renderDialog } from "@basenative/components";
import { fromHTML } from "../lib/dom.js";

const HELP_CONTENT = `
  <header>
    <h2 id="help-title" data-bn-region="title" data-tone="help">HOW TO PLAY</h2>
    <p data-bn-region="subtitle">One subject. One phrase. No mercy.</p>
  </header>
  <div data-bn-region="help-body">
    <p><b>1 &middot; Type into tiles. </b>Pick a word, type its letters into the tiles. Press Enter or tap GO.</p>
    <p><b data-tone="green">2 &middot; Greens lock in. </b>Letters in the right spot stay revealed across attempts. Letters known to be in the phrase pile up below.</p>
    <p><b data-tone="yellow">3 &middot; Stake tiles 2&times;. </b>Tap any tile you've typed before submitting — right pays double, wrong costs double.</p>
    <p><b data-tone="green">4 &middot; Cold solves earn ⚡. </b>Solve a word with no wrong attempts → tap any unrevealed tile in any unsolved word for a free letter.</p>
    <p><b data-tone="red">5 &middot; ALL IN. </b>Shove the whole phrase. Right = +8 × every unrevealed tile. Wrong = game over.</p>
  </div>
  <button type="button" data-bn-button="primary" data-bn-action="help-close">Got it</button>
`;

/**
 * The help dialog's full markup as a plain string — no signals, no DOM,
 * so it's testable on its own (renderDialog is a pure string renderer).
 * Exported so tests can assert on it without a document.
 */
export function helpDialogHtml() {
  return renderDialog({
    id: "help-dialog",
    modal: true,
    closable: false,
    content: HELP_CONTENT,
  });
}

export function createHelpModal({ open, onClose }) {
  const dlg = /** @type {HTMLDialogElement} */ (fromHTML(helpDialogHtml()));
  /* renderDialog() (components 0.7.0) emits aria-labelledby only for
     its own `title` slot; this dialog keeps its title inside `content`
     (see above), so the label is pointed at that h2 here. */
  dlg.setAttribute("aria-labelledby", "help-title");
  dlg.addEventListener("close", onClose);
  dlg.addEventListener("click", (e) => { if (e.target === dlg) onClose(); });
  dlg.querySelector('[data-bn-action="help-close"]').addEventListener("click", onClose);

  effect(() => {
    const isOpen = open();
    if (isOpen && !dlg.open) dlg.showModal();
    else if (!isOpen && dlg.open) dlg.close();
  });

  return dlg;
}
